# Vagrantfile
UBUNTU="bento/ubuntu-24.04"

Vagrant.configure(2) do |config|
  NodeType1 = 1
  (1..NodeType1).each do |type1_id|
    config.vm.define "type1#{type1_id}" do |type1_vm|
      type1_vm.vm.box = UBUNTU
      type1_vm.vm.hostname = "type1#{type1_id}.example.com"
      type1_vm.vm.network "private_network", ip: "192.168.56.10#{type1_id}"
      type1_vm.vm.provider "virtualbox" do |v|
        v.name = "type1#{type1_id}"
        v.memory = 2048
        v.cpus = 3
      end
      type1_vm.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
